# See README.md for usage information
version: '3'

services:
  vv-java-tomcat:
    image: quay.io/snowbound/virtualviewer:5.12-tomcat9.0-jdk11-latest
#    image: quay.io/snowbound/virtualviewer:5.12.0.1030-tomcat9.0-jdk11
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ehcache_vol:/tmp/vvcache
      - vvtmp_vol:/tmp/vvtmp
      - ./classes:/snowbound/classes:ro
#      - ./fonts:/snowbound/fonts:ro
#      - ./tomcat:/snowbound/tomcat:ro
#      - ./user-config:/snowbound/user-config:ro
#      - ./WEB-INF:/snowbound/WEB-INF:ro

volumes:
  ehcache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  vvtmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs