FROM quay.io/alfresco/alfresco-share:23.2.2

COPY ./amps/snowbound-share-5.13.0.amp /usr/local/tomcat/amps_share

RUN java -jar /usr/local/tomcat/alfresco-mmt/alfresco-mmt*.jar install \
    /usr/local/tomcat/amps_share/ /usr/local/tomcat/webapps/share -directory -nobackup -force
